# Generated by Django 4.2.2 on 2023-06-24 15:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_provincia_municipio_bairro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=14)),
                ('data_matricula', models.DateField(default=datetime.datetime(2023, 6, 24, 16, 8, 7, 539899), verbose_name='Data de Matrícula')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contato1', models.IntegerField(max_length=9)),
                ('contato2', models.IntegerField(max_length=9)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.bairro')),
            ],
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('titulo', models.CharField(max_length=50)),
                ('contato1', models.IntegerField(max_length=9)),
                ('contato2', models.IntegerField(max_length=9)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.bairro')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_aluno', models.IntegerField(max_length=30, verbose_name='Número de Alunos')),
                ('horario', models.DateTimeField(verbose_name='Horário')),
                ('duracao', models.DurationField(verbose_name='Duração')),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateTimeField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.atividade')),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.instrutor')),
            ],
        ),
        migrations.CreateModel(
            name='Equipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.turma')),
            ],
        ),
    ]
