# Generated by Django 4.2.2 on 2023-06-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_remove_bairro_provincia_alter_aluno_contato1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='contato1',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Contato Príncipal'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='contato2',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Contato Alternatico'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_matricula',
            field=models.DateField(verbose_name='Data de Matrícula'),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='contato1',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Contato Príncipal'),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='contato2',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Contato Alternatico'),
        ),
    ]
