# Generated by Django 4.2.2 on 2023-06-26 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_aluno_contato1_alter_aluno_contato2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_matricula',
            field=models.DateField(default=datetime.datetime(2023, 6, 26, 1, 56, 12, 386421), verbose_name='Data de Matrícula'),
        ),
    ]
