# Generated by Django 4.2.2 on 2023-06-26 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_aluno_data_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_matricula',
            field=models.DateField(default=datetime.datetime(2023, 6, 26, 2, 9, 50, 257802), verbose_name='Data de Matrícula'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='documento',
            field=models.CharField(help_text='número do bi', max_length=14),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='documento',
            field=models.CharField(help_text='número do bi', max_length=14),
        ),
    ]
