# Generated by Django 4.2.2 on 2023-07-04 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_remove_aluno_documento_remove_instrutor_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_matricula',
            field=models.DateField(default=datetime.datetime(2023, 7, 4, 10, 50, 26, 847368), verbose_name='Data de Matrícula'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
